get the api and worked with it for the display and add score
NickEmma/leaderboard pull request #2
Opened 2022-07-20 13:48 UTC by NickEmma

- Read the [Leaderboard API documentation and to learn how to use this API..
- i Implemented the "Refresh" button (receiving data from the API and parsing the JSON).
- i Implemented the form "Submit" button (sending data to the API).

- Use async and await JavaScript features to consume the API.

2022-07-20 17:37 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽  @NickEmma 

Good job working on the project so far! 
✔️ Your app works as expected
✔️ You used arrow functions
However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/4GXUa4U05Q0JAM972c/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-20 17:37 UTC, Ghiftee commented on src/display.js
> +/* eslint-disable import/extensions */
- [ ] Kindly do not disable this linter as it helps ensure we write clean code. You can consider removing ```.js``` from line 3 so that it is written this way: ```import API_URL from './working';``` this should solve the error.

2022-07-20 17:37 UTC, Ghiftee commented on src/index.js
>  /* eslint-disable import/extensions */
- [ ] Kindly do not disable this linter as it helps ensure we write clean code. You can consider removing ```.js``` from line 5 - 7 so that it is written this way: ```import displayScore from './crud';``` ```import API_URL from './working';``` ```import postData from './display';``` this should solve the error.
- [ ] Also, kindly do not disable the linter on line 1.

2022-07-21 10:12 UTC, youmari approved these changes
# Project Approved :trophy: :tada: 🟢 

Hi @NickEmma 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-21 10:20 UTC, merged